name: maxi_framework
description: Base library for Maximiliano Camilo's projects made in pure Dart or Flutter. Here you will find the vital structures and functionalities, as well as the system interfaces
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  meta: ^1.17.0
  path: ^1.9.1
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
